#!/bin/bash

# Installation script for passwordless fan control
# This script sets up the necessary sudoers configuration

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUDOERS_FILE="/etc/sudoers.d/fan-control"
TARGET_USER="${SUDO_USER:-$USER}"

echo "=== Fan Control Sudoers Installation ==="
echo "This script will install the sudoers configuration to allow"
echo "passwordless fan control for user '${TARGET_USER}'."
echo ""

# Check if we're running as root or with sudo
if [ "$EUID" -ne 0 ]; then
    echo "Error: This script must be run with sudo privileges."
    echo "Please run: sudo $0"
    exit 1
fi

echo "Installing sudoers configuration to: $SUDOERS_FILE"

# Create the sudoers file with proper permissions
cat > "$SUDOERS_FILE" << EOF
# Allow $TARGET_USER to control fan PWM without password
# Generated by fan control installation script

$TARGET_USER ALL=(root) NOPASSWD: /usr/bin/tee /sys/class/hwmon/hwmon*/pwm*_enable
$TARGET_USER ALL=(root) NOPASSWD: /usr/bin/tee /sys/class/hwmon/hwmon*/pwm*
EOF

# Set proper permissions on the sudoers file
chmod 440 "$SUDOERS_FILE"
chown root:root "$SUDOERS_FILE"

# Validate the sudoers file
if visudo -c -f "$SUDOERS_FILE"; then
    echo "✓ Sudoers configuration installed successfully!"
    echo "✓ Configuration file: $SUDOERS_FILE"
    echo ""
    echo "You can now use the fan control keybinds:"
    echo "  Ctrl+Alt+F - Open fan control GUI"
    echo "  Ctrl+Alt+1 - Silent mode (30%)"
    echo "  Ctrl+Alt+2 - Quiet mode (50%)"
    echo "  Ctrl+Alt+3 - Performance mode (80%)"
    echo "  Ctrl+Alt+0 - Auto mode"
    echo "  Ctrl+Alt+T - Temperature monitoring"
    echo ""
    echo "Testing fan control access..."

    # Try to locate a hwmon path like the GUI scripts use
    PWM_BASE_PATH=$(find /sys/class/hwmon/ -name "hwmon*" -exec sh -c 'if [ -f "$1/name" ] && grep -qi "nct6798" "$1/name" 2>/dev/null; then echo "$1"; fi' _ {} \; | head -1)
    if [ -z "$PWM_BASE_PATH" ]; then
        PWM_BASE_PATH="/sys/class/hwmon/hwmon5"
    fi

    TEST_PWM_ENABLE=$(find "$PWM_BASE_PATH" -maxdepth 1 -type f -name 'pwm*_enable' | sort | head -n1)

    if [ -n "$TEST_PWM_ENABLE" ]; then
        # Switch to manual mode (1), then back to auto (5) using the target user's passwordless sudo
        if sudo -n -u "$TARGET_USER" bash -lc "echo 1 | sudo -n /usr/bin/tee '$TEST_PWM_ENABLE' >/dev/null 2>&1"; then
            echo "✓ Fan control access test: PASSED"
            sudo -n -u "$TARGET_USER" bash -lc "echo 5 | sudo -n /usr/bin/tee '$TEST_PWM_ENABLE' >/dev/null 2>&1"
        else
            echo "✗ Fan control access test: FAILED"
            echo "  You may need to log out and back in for the changes to take effect."
        fi
    else
        echo "⚠ Could not locate a pwm*_enable file under $PWM_BASE_PATH to test."
        echo "  The sudoers entry is installed and validated; try the GUI or fan_control.sh."
    fi
else
    echo "✗ Error: Invalid sudoers configuration!"
    echo "  Removing the faulty configuration file..."
    rm -f "$SUDOERS_FILE"
    exit 1
fi

echo ""
echo "Installation complete!"
