#!/bin/bash

# Installation script for passwordless fan control
# This script sets up the necessary sudoers configuration

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUDOERS_FILE="/etc/sudoers.d/fan-control"

echo "=== Fan Control Sudoers Installation ==="
echo "This script will install the sudoers configuration to allow"
echo "passwordless fan control for user 'sasha'."
echo ""

# Check if we're running as root or with sudo
if [ "$EUID" -ne 0 ]; then
    echo "Error: This script must be run with sudo privileges."
    echo "Please run: sudo $0"
    exit 1
fi

echo "Installing sudoers configuration to: $SUDOERS_FILE"

# Create the sudoers file with proper permissions
cat > "$SUDOERS_FILE" << 'EOF'
# Allow sasha to control fan PWM without password
# Generated by fan control installation script

sasha ALL=(root) NOPASSWD: /usr/bin/tee /sys/devices/platform/nct6775.656/hwmon/hwmon3/pwm*_enable
sasha ALL=(root) NOPASSWD: /usr/bin/tee /sys/devices/platform/nct6775.656/hwmon/hwmon3/pwm*
sasha ALL=(root) NOPASSWD: /usr/bin/tee /sys/devices/platform/nct6775.656/hwmon/hwmon4/pwm*_enable
sasha ALL=(root) NOPASSWD: /usr/bin/tee /sys/devices/platform/nct6775.656/hwmon/hwmon4/pwm*
sasha ALL=(root) NOPASSWD: /usr/bin/tee /sys/devices/platform/nct6775.656/hwmon/hwmon5/pwm*_enable
sasha ALL=(root) NOPASSWD: /usr/bin/tee /sys/devices/platform/nct6775.656/hwmon/hwmon5/pwm*
EOF

# Set proper permissions on the sudoers file
chmod 440 "$SUDOERS_FILE"
chown root:root "$SUDOERS_FILE"

# Validate the sudoers file
if visudo -c -f "$SUDOERS_FILE"; then
    echo "✓ Sudoers configuration installed successfully!"
    echo "✓ Configuration file: $SUDOERS_FILE"
    echo ""
    echo "You can now use the fan control keybinds:"
    echo "  Ctrl+Alt+F - Open fan control GUI"
    echo "  Ctrl+Alt+1 - Silent mode (30%)"
    echo "  Ctrl+Alt+2 - Quiet mode (50%)"
    echo "  Ctrl+Alt+3 - Performance mode (80%)"
    echo "  Ctrl+Alt+0 - Auto mode"
    echo "  Ctrl+Alt+T - Temperature monitoring"
    echo ""
    echo "Testing fan control access..."
    
    # Test if the user can now control fans without password
    sudo -u sasha /usr/bin/tee /sys/devices/platform/nct6775.656/hwmon/hwmon4/pwm1_enable <<< "1" >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo "✓ Fan control access test: PASSED"
        # Reset to auto mode
        sudo -u sasha /usr/bin/tee /sys/devices/platform/nct6775.656/hwmon/hwmon4/pwm1_enable <<< "5" >/dev/null 2>&1
    else
        echo "✗ Fan control access test: FAILED"
        echo "  You may need to log out and back in for the changes to take effect."
    fi
else
    echo "✗ Error: Invalid sudoers configuration!"
    echo "  Removing the faulty configuration file..."
    rm -f "$SUDOERS_FILE"
    exit 1
fi

echo ""
echo "Installation complete!"
